/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dmens.pokeno.Board;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author cclp94
 */
public class PokemonCardPanel extends javax.swing.JPanel {
    private String POKEMON_ICON_IMAGE = "data/images/pokemon.png";

    /**
     * Creates new form PokemonCardPanel
     */
    public PokemonCardPanel() {
        initComponents();
    }
    
    public PokemonCardPanel(String name, int HP, String... abilities){
        initComponents();
        cardName.setText(name);
        ImageIcon imageIcon = null;
        try{
        imageIcon = new ImageIcon(ImageIO.read(new File(POKEMON_ICON_IMAGE)));
        }catch(IOException e){
            e.printStackTrace();
        }
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(120, 120,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg);
        imageLabel.setIcon(imageIcon);
        this.HP.setText(Integer.toString(HP));
        // TODO Add Abilities description
        //this.ability1.setText(abilities[0]);
        //this.ability2.setText(abilities[1]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardName = new javax.swing.JLabel();
        HP = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        ability1 = new javax.swing.JLabel();
        ability2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(90, 307));

        cardName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cardName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cardName.setText("Name");
        cardName.setAlignmentY(0.0F);
        cardName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cardName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        HP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        HP.setText("HP");
        HP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HP.setFocusable(false);
        HP.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imageLabel.setPreferredSize(new java.awt.Dimension(80, 80));

        ability1.setText("Ability 1");
        ability1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        ability2.setText("Ability 2");
        ability2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ability1)
                            .addComponent(ability2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cardName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(HP, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardName)
                    .addComponent(HP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ability1)
                .addGap(34, 34, 34)
                .addComponent(ability2)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HP;
    private javax.swing.JLabel ability1;
    private javax.swing.JLabel ability2;
    private javax.swing.JLabel cardName;
    private javax.swing.JLabel imageLabel;
    // End of variables declaration//GEN-END:variables
}
